export type Subject = "biochem" | "cell" | "cross";
export type Mode = "foundation" | "metabolism" | "nitrogen" | "information" | "cell";

export type KnowledgeNode = {
  id: string;
  label: string;
  short: string;
  x: number;
  y: number;
  size: number;
  subject: Subject;
  priority: 1 | 2 | 3;
  mode: Mode;
  source: "河南农资料高频" | "河南农课件" | "河南农既有大纲" | "教材主线" | "同类农校预测";
  summary: string;
  location: string;
  equation: string;
  enzymes: { name: string; note: string; type?: string }[];
  flags: string[];
  exam: string;
  crossLinks?: { id: string; question: string }[];
};

export const modes: { id: Mode; label: string; caption: string }[] = [
  { id: "foundation", label: "分子基础", caption: "蛋白质 · 核酸 · 酶" },
  { id: "metabolism", label: "能量代谢", caption: "糖 · 脂 · 呼吸链" },
  { id: "nitrogen", label: "含氮代谢", caption: "氨基酸 · 核苷酸" },
  { id: "information", label: "遗传信息", caption: "复制 · 表达 · 调控" },
  { id: "cell", label: "细胞系统", caption: "下期补充 · 现为预览" },
];

const shared = {
  size: 58,
  priority: 2 as const,
  source: "教材主线" as const,
};

export const nodes: KnowledgeNode[] = [
  {
    ...shared, id: "amino-acid", label: "α-氨基酸", short: "AA", x: 12, y: 22, size: 66, subject: "biochem", priority: 3, mode: "foundation", source: "河南农资料高频",
    summary: "蛋白质的基本单元。除甘氨酸外，蛋白质氨基酸的 α-碳通常具有手性；侧链决定酸碱性、极性与反应性。",
    location: "游离于细胞氨基酸代谢库，或通过肽键进入蛋白质",
    equation: "H₂N—CH(R)—COOH ⇌ ⁺H₃N—CH(R)—COO⁻",
    enzymes: [{ name: "氨酰-tRNA 合成酶", note: "识别氨基酸与对应 tRNA，是翻译准确性的第一道关", type: "ATP依赖活化" }],
    flags: ["L-α-氨基酸", "两性电解质", "侧链分类", "甘氨酸无手性"],
    exam: "常以分类、缩写、酸碱性和离子交换洗脱顺序出题；回答时先看溶液 pH 与氨基酸 pI 的关系。",
    crossLinks: [{ id: "isoelectric-point", question: "给定 pH 和不同 pI 的氨基酸，判断净电荷、迁移方向与离子交换洗脱次序。" }],
  },
  {
    ...shared, id: "isoelectric-point", label: "等电点", short: "pI", x: 31, y: 13, size: 58, subject: "biochem", priority: 3, mode: "foundation", source: "河南农资料高频",
    summary: "分子平均净电荷为零时的 pH。pH 低于 pI 时偏正电，高于 pI 时偏负电；等电点附近常表现为溶解度最低。",
    location: "氨基酸/蛋白质水溶液与电泳、离子交换分离体系",
    equation: "pH < pI：净正电；pH = pI：净电荷≈0；pH > pI：净负电",
    enzymes: [{ name: "等电聚焦", note: "蛋白质在 pH 梯度中迁移到自身 pI 处停止", type: "分析方法" }],
    flags: ["名词解释高频", "电泳方向", "离子交换", "溶解度最低"],
    exam: "结合阳/阴离子交换树脂考洗脱顺序；必须说明载体电荷、样品净电荷和盐/pH 梯度。",
  },
  {
    ...shared, id: "peptide-bond", label: "肽键", short: "—CO—NH—", x: 51, y: 12, size: 61, subject: "biochem", priority: 3, mode: "foundation", source: "河南农课件",
    summary: "羧基与氨基脱水形成的酰胺键，因共振具有部分双键性质，通常呈反式、近似平面且不能自由旋转。",
    location: "多肽主链；平面之间可绕 Cα—N 与 Cα—C 键转动",
    equation: "—COOH + H₂N— → —CO—NH— + H₂O",
    enzymes: [{ name: "肽基转移酶中心", note: "核糖体大亚基 rRNA 催化肽键形成", type: "核酶" }],
    flags: ["部分双键", "肽平面", "反式", "方向 N→C"],
    exam: "解释肽键为什么不能自由旋转，以及主链构象由 φ、ψ 二面角决定。",
  },
  {
    ...shared, id: "protein-structure", label: "蛋白质结构层次", short: "1°→4°", x: 69, y: 23, size: 82, subject: "biochem", priority: 3, mode: "foundation", source: "河南农资料高频",
    summary: "一级序列决定折叠倾向，高级结构提供功能界面；二级结构靠主链氢键，三级/四级结构由多种非共价力与二硫键稳定。",
    location: "从单条多肽的局部构象到多亚基复合体",
    equation: "一级序列 → 局部二级结构 → 单链三级结构 → 亚基四级结构 → 功能",
    enzymes: [{ name: "分子伴侣", note: "帮助蛋白避免错误聚集，但不提供最终结构信息", type: "折叠辅助" }],
    flags: ["结构决定功能", "Anfinsen实验", "亚基", "二硫键"],
    exam: "结合镰刀型贫血、核糖核酸酶复性或血红蛋白说明一级结构与功能的关系。",
    crossLinks: [{ id: "denaturation", question: "比较变性与水解，说明一级结构是否改变、哪些作用力被破坏以及能否复性。" }],
  },
  {
    ...shared, id: "alpha-helix", label: "α螺旋与β折叠", short: "α / β", x: 88, y: 13, size: 62, subject: "biochem", priority: 3, mode: "foundation", source: "河南农课件",
    summary: "α螺旋由同一链内 i→i+4 氢键稳定；β折叠由相邻肽段间主链氢键稳定，可平行或反平行。",
    location: "蛋白质二级结构；氢键发生在主链 C=O 与 N—H 之间",
    equation: "α螺旋：3.6 残基/圈；β折叠：侧链交替伸向片层两侧",
    enzymes: [{ name: "脯氨酸 / 甘氨酸", note: "Pro 常打断 α 螺旋；Gly 构象自由度大，常见于转角", type: "构象影响" }],
    flags: ["主链氢键", "3.6残基/圈", "平行/反平行", "Ramachandran图"],
    exam: "区分二级结构与结构域/亚基，写清稳定力来自主链而非侧链。",
  },
  {
    ...shared, id: "denaturation", label: "蛋白质变性", short: "DENAT", x: 86, y: 43, size: 67, subject: "biochem", priority: 3, mode: "foundation", source: "河南农资料高频",
    summary: "物理或化学因素破坏天然构象与活性，通常不切断肽键；能否复性取决于一级结构完整性、环境与聚集程度。",
    location: "加热、极端 pH、尿素、胍盐、去污剂或还原剂处理体系",
    equation: "天然态 N ⇌ 展开态 U → 聚集/沉淀（部分条件可逆）",
    enzymes: [{ name: "β-巯基乙醇 / DTT", note: "还原二硫键；与尿素配合可展开核糖核酸酶", type: "还原剂" }],
    flags: ["活性丧失", "不切肽键", "溶解度下降", "复性条件"],
    exam: "对比变性、沉淀与水解；用 RNase 复性实验说明一级结构包含折叠信息。",
  },
  {
    ...shared, id: "hemoglobin", label: "血红蛋白", short: "Hb", x: 68, y: 54, size: 66, subject: "biochem", priority: 3, mode: "foundation", source: "河南农资料高频",
    summary: "α₂β₂ 四聚体呈协同结合氧和别构调节；H⁺、CO₂ 与 2,3-BPG 降低氧亲和力，帮助组织卸氧。",
    location: "红细胞胞质；血红素 Fe²⁺直接结合 O₂",
    equation: "T 态（低亲和）⇌ R 态（高亲和）；结合曲线为 S 形",
    enzymes: [{ name: "2,3-BPG", note: "结合去氧 Hb 中央腔，稳定 T 态并右移氧解离曲线", type: "别构效应物" }],
    flags: ["协同效应", "Bohr效应", "别构蛋白", "镰刀型贫血"],
    exam: "比较 Hb 与肌红蛋白的亚基、结合曲线和生理功能；联系结构改变导致功能异常。",
  },
  {
    ...shared, id: "protein-purification", label: "蛋白质分离纯化", short: "PURIFY", x: 47, y: 43, size: 76, subject: "biochem", priority: 3, mode: "foundation", source: "河南农资料高频",
    summary: "把‘性质差异’翻译成方法：大小用凝胶过滤/SDS-PAGE，电荷用离子交换，特异结合用亲和层析；浓缩与脱盐解决的是不同问题。",
    location: "粗提、分级、层析、纯度与活性鉴定的实验流程",
    equation: "低浓度含盐样品：超滤浓缩 → 透析/脱盐柱除盐 → 活性与纯度验证",
    enzymes: [{ name: "SDS-PAGE", note: "变性后主要按亚基分子量分离；两条带不必然说明样品不纯", type: "电泳" }, { name: "凝胶过滤", note: "天然状态按水动力体积分离，大分子先流出", type: "层析" }],
    flags: ["实验设计高频", "先定目标", "比活性", "方法组合"],
    exam: "给出分子量、pI、盐浓度或配体信息，设计流程并逐步说明原理、先后顺序与验证指标。",
  },
  {
    ...shared, id: "nucleic-acid", label: "核酸结构", short: "DNA/RNA", x: 27, y: 47, size: 73, subject: "biochem", priority: 3, mode: "foundation", source: "河南农资料高频",
    summary: "核苷酸经 3′,5′-磷酸二酯键连接。DNA 双链反向平行并遵守碱基互补；RNA 的 2′-OH 使其更易水解并可形成复杂局部结构。",
    location: "DNA 主要储存遗传信息；RNA 同时承担信息、结构、识别与催化功能",
    equation: "核苷 + 磷酸 = 核苷酸；核苷酸链方向 5′→3′",
    enzymes: [{ name: "核酸酶", note: "内切酶从链内切，外切酶从末端逐步切除", type: "磷酸二酯键水解" }],
    flags: ["反向平行", "碱基互补", "3′,5′键", "RNA可为核酶"],
    exam: "比较 DNA 与 RNA 的糖、碱基、结构、稳定性和功能；辨析核苷、核苷酸与碱基。",
    crossLinks: [{ id: "dna-denaturation", question: "从氢键、碱基堆积和 GC 含量解释 DNA 的 Tm、增色效应与复性条件。" }],
  },
  {
    ...shared, id: "dna-denaturation", label: "DNA变性与复性", short: "Tm", x: 9, y: 66, size: 63, subject: "biochem", priority: 3, mode: "foundation", source: "河南农资料高频",
    summary: "升温或极端 pH 使双链解开而磷酸二酯键不断；260 nm 吸光度升高为增色效应。缓慢降温且序列互补时可退火复性。",
    location: "核酸溶液、PCR 变性/退火与分子杂交实验",
    equation: "双链 DNA ⇌ 两条单链；GC↑、离子强度↑、链长↑通常使 Tm↑",
    enzymes: [{ name: "分子杂交", note: "互补核酸链退火形成双链，用于探针检测与序列分析", type: "非酶促配对" }],
    flags: ["Tm名词高频", "增色效应", "GC含量", "核酸杂交"],
    exam: "给定 GC 含量、盐浓度或错配程度判断 Tm 变化，并区分变性与降解。",
  },
  {
    ...shared, id: "enzyme", label: "酶与全酶", short: "ENZYME", x: 26, y: 74, size: 74, subject: "biochem", priority: 3, mode: "foundation", source: "河南农资料高频",
    summary: "酶降低活化能而不改变反应平衡；全酶由酶蛋白与辅助因子组成，前者决定底物特异性，后者常传递电子或基团。",
    location: "细胞各区室；活性依赖正确构象与适宜微环境",
    equation: "E + S ⇌ ES → E + P；全酶 = 脱辅酶 + 辅因子",
    enzymes: [{ name: "活性中心", note: "底物结合与催化基团构成的三维微环境", type: "催化核心" }],
    flags: ["高效", "专一", "不改平衡", "酶活力/比活力"],
    exam: "区分酶、核酶、辅酶、辅基、金属酶与金属激活酶；常配合酶活力单位考查。",
  },
  {
    ...shared, id: "michaelis", label: "米氏动力学", short: "Km / Vmax", x: 48, y: 72, size: 76, subject: "biochem", priority: 3, mode: "foundation", source: "河南农资料高频",
    summary: "在简单米氏条件下，Km 是 v=Vmax/2 时的底物浓度；同一酶对不同底物比较时，Km 较小通常表示表观亲和力较高。",
    location: "初速率、底物远大于酶、稳态近似的体外动力学体系",
    equation: "v = Vmax[S] / (Km + [S])；kcat = Vmax/[E]t",
    enzymes: [{ name: "Lineweaver–Burk 图", note: "1/v 对 1/[S] 作图；便于辨析抑制类型但放大低浓度误差", type: "双倒数图" }],
    flags: ["Km名词高频", "半最大速率", "kcat", "初速度"],
    exam: "画米氏曲线或双倒数图，判断 Km/Vmax 改变并解释物理意义。",
    crossLinks: [{ id: "enzyme-inhibition", question: "分别判断竞争、非竞争和反竞争抑制对 Km、Vmax 及双倒数图交点的影响。" }],
  },
  {
    ...shared, id: "enzyme-inhibition", label: "酶抑制", short: "INHIB", x: 69, y: 78, size: 69, subject: "biochem", priority: 3, mode: "foundation", source: "河南农资料高频",
    summary: "竞争抑制剂争夺游离酶活性中心；纯非竞争对 E/ES 亲和相同；反竞争只结合 ES。先判断结合对象，再推 Km 与 Vmax。",
    location: "酶动力学与代谢/药物调控体系",
    equation: "竞争：Km↑ Vmax不变；纯非竞争：Km不变 Vmax↓；反竞争：Km↓ Vmax↓",
    enzymes: [{ name: "可逆抑制剂", note: "通过非共价作用降低活性；提高底物只能克服竞争抑制", type: "动力学辨析" }],
    flags: ["图像题", "Km变化", "Vmax变化", "结合对象"],
    exam: "给曲线或实验数据判断抑制类型，不能只背结论，要写抑制剂结合 E、ES 或两者。",
  },
  {
    ...shared, id: "coenzyme", label: "维生素与辅酶", short: "COENZ", x: 87, y: 75, size: 75, subject: "biochem", priority: 3, mode: "foundation", source: "河南农资料高频",
    summary: "水溶性维生素常转化为辅酶：B₁→TPP 传醛基，B₂→FAD/FMN 传氢，B₃→NAD(P)⁺，B₆→PLP 转氨，生物素传 CO₂。",
    location: "与特定酶蛋白结合，参与电子、原子或基团转移",
    equation: "B₁→TPP；B₂→FAD/FMN；B₃→NAD⁺/NADP⁺；B₅→CoA；B₆→PLP；B₇→生物素；B₉→THF",
    enzymes: [{ name: "辅酶A", note: "以高能硫酯形式携带酰基，连接糖、脂与氨基酸代谢", type: "酰基载体" }],
    flags: ["配对题高频", "辅酶A简答", "电子/基团载体", "缺乏症次要"],
    exam: "按‘维生素—辅酶形式—转移基团—代表反应’四联表复习，避免只背名称。",
  },

  {
    ...shared, id: "aa-pool", label: "氨基酸代谢库", short: "AA POOL", x: 49, y: 13, size: 72, subject: "biochem", priority: 3, mode: "nitrogen", source: "河南农课件",
    summary: "食物蛋白、体蛋白降解与体内合成共同进入氨基酸库；主要去路是合成蛋白/含氮物，或脱氮后氧化碳骨架。",
    location: "全身组织间动态交换，不存在专门的氨基酸储存形式",
    equation: "氨基酸 → 含氮部分（尿素/合成） + 碳骨架（糖/酮体/氧化）",
    enzymes: [{ name: "蛋白酶体 / 溶酶体", note: "分别偏向短寿命异常蛋白与长寿命/胞外来源蛋白降解", type: "蛋白周转" }],
    flags: ["无专门储存", "氮与碳分流", "蛋白周转", "饥饿状态"],
    exam: "画出氨基酸来源和四类去路，随后分别展开氮的运输/排泄和碳骨架归宿。",
  },
  {
    ...shared, id: "transamination", label: "转氨基作用", short: "TRANSAM", x: 28, y: 28, size: 69, subject: "biochem", priority: 3, mode: "nitrogen", source: "河南农资料高频",
    summary: "氨基酸把氨基转给 α-酮酸，常汇集为谷氨酸；反应通常可逆，不直接释放游离氨。",
    location: "胞质与线粒体；多组织参与",
    equation: "氨基酸 + α-酮戊二酸 ⇌ α-酮酸 + 谷氨酸",
    enzymes: [{ name: "转氨酶", note: "以 PLP 为辅酶；ALT/AST 连接氨基酸与糖代谢", type: "氨基转移" }],
    flags: ["PLP", "可逆", "不放游离氨", "汇集谷氨酸"],
    exam: "比较转氨、氧化脱氨和联合脱氨，写清受氨体、辅酶与是否产生 NH₄⁺。",
    crossLinks: [{ id: "plp", question: "说明 PLP 如何暂存氨基，并联系转氨、脱羧和消旋反应。" }],
  },
  {
    ...shared, id: "plp", label: "磷酸吡哆醛", short: "PLP", x: 9, y: 42, size: 57, subject: "biochem", priority: 3, mode: "nitrogen", source: "河南农资料高频",
    summary: "维生素 B₆ 的活性辅酶，以席夫碱形式稳定氨基酸 α-碳负离子中间体，参与转氨、脱羧等反应。",
    location: "转氨酶等氨基酸代谢酶活性中心",
    equation: "酶-PLP + 氨基酸 ⇌ 酶-PMP + α-酮酸",
    enzymes: [{ name: "氨基酸脱羧酶", note: "PLP 依赖，生成生物胺与 CO₂", type: "脱羧" }],
    flags: ["维生素B₆", "席夫碱", "转氨", "脱羧"],
    exam: "维生素—辅酶—反应类型配对的重点分子。",
  },
  {
    ...shared, id: "glutamate", label: "谷氨酸", short: "Glu", x: 49, y: 41, size: 76, subject: "biochem", priority: 3, mode: "nitrogen", source: "河南农资料高频",
    summary: "多数氨基酸氮的汇集点，也是氧化脱氨、谷氨酰胺合成和多种氨基酸生物合成的枢纽。",
    location: "胞质与线粒体氮代谢交汇处",
    equation: "α-酮戊二酸 + NH₄⁺ + NAD(P)H ⇌ 谷氨酸 + NAD(P)⁺ + H₂O",
    enzymes: [{ name: "谷氨酸脱氢酶", note: "连接游离氨与 TCA 碳骨架；受能荷别构调节", type: "氧化脱氨/还原氨化" }],
    flags: ["氮汇集", "α-酮戊二酸", "GDH", "代谢枢纽"],
    exam: "把转氨、谷氨酸氧化脱氨和尿素循环串成氮排泄主线。",
  },
  {
    ...shared, id: "oxidative-deamination", label: "氧化脱氨", short: "DEAM", x: 70, y: 29, size: 65, subject: "biochem", priority: 3, mode: "nitrogen", source: "河南农资料高频",
    summary: "谷氨酸脱氢酶把谷氨酸转为 α-酮戊二酸并释放 NH₄⁺；与转氨合称联合脱氨。",
    location: "主要在线粒体；肝、肾等组织活跃",
    equation: "谷氨酸 + NAD(P)⁺ + H₂O ⇌ α-酮戊二酸 + NH₄⁺ + NAD(P)H",
    enzymes: [{ name: "L-谷氨酸脱氢酶", note: "ATP/GTP 抑制，ADP/GDP 激活，反映细胞能荷", type: "别构酶" }],
    flags: ["释放游离氨", "NAD(P)⁺", "联合脱氨", "可逆"],
    exam: "常与转氨基作用对比；写出能荷对 GDH 的调节方向。",
  },
  {
    ...shared, id: "urea-cycle", label: "尿素循环", short: "UREA", x: 86, y: 45, size: 82, subject: "biochem", priority: 3, mode: "nitrogen", source: "河南农资料高频",
    summary: "把有毒氨转为尿素。一个氮来自游离 NH₄⁺，另一个来自天冬氨酸；跨线粒体与胞质完成。",
    location: "肝细胞：前两步在线粒体，后三步在胞质",
    equation: "NH₄⁺ + HCO₃⁻ + Asp + 3 ATP → 尿素 + 延胡索酸 + 2 ADP + AMP（4个高能磷酸键）",
    enzymes: [{ name: "氨甲酰磷酸合成酶Ⅰ", note: "线粒体限速酶；需 N-乙酰谷氨酸激活", type: "限速步骤" }, { name: "精氨酸酶", note: "水解精氨酸生成尿素与鸟氨酸", type: "循环终步" }],
    flags: ["2个氮来源", "4个高能键", "跨区室", "与TCA相连"],
    exam: "写反应顺序、区室、氮来源、能量成本，并通过天冬氨酸-精氨代琥珀酸旁路联系 TCA。",
    crossLinks: [{ id: "one-carbon", question: "比较尿素循环处理氮与一碳单位转移碳的载体、来源和主要用途。" }],
  },
  {
    ...shared, id: "cps1", label: "氨甲酰磷酸", short: "CPS-I", x: 90, y: 73, size: 59, subject: "biochem", priority: 3, mode: "nitrogen", source: "河南农资料高频",
    summary: "尿素循环第一步由 CPS-I 在基质利用游离氨生成；嘧啶合成用胞质 CPS-II，氮源和定位不同。",
    location: "CPS-I 在线粒体基质；CPS-II 在胞质",
    equation: "NH₄⁺ + HCO₃⁻ + 2 ATP → 氨甲酰磷酸 + 2 ADP + Pi",
    enzymes: [{ name: "CPS-I / CPS-II", note: "I 用 NH₄⁺、参与尿素循环；II 用谷氨酰胺、参与嘧啶合成", type: "易混比较" }],
    flags: ["NAG激活", "耗2 ATP", "尿素/嘧啶分流", "区室辨析"],
    exam: "比较 CPS-I 与 CPS-II 的区室、氮源、调节和代谢用途。",
  },
  {
    ...shared, id: "one-carbon", label: "一碳单位", short: "1-C / THF", x: 67, y: 68, size: 72, subject: "biochem", priority: 3, mode: "nitrogen", source: "河南农资料高频",
    summary: "除 CO₂ 外多种单碳基团由四氢叶酸携带，来自丝氨酸、甘氨酸等，供嘌呤、dTMP 和甲硫氨酸再生。",
    location: "胞质/线粒体叶酸循环，与氨基酸和核苷酸合成交叉",
    equation: "Ser + THF ⇌ Gly + N⁵,N¹⁰-亚甲基-THF",
    enzymes: [{ name: "丝氨酸羟甲基转移酶", note: "PLP 依赖，生成甘氨酸与亚甲基-THF", type: "一碳转移" }],
    flags: ["THF载体", "嘌呤C2/C8", "dTMP", "甲基化"],
    exam: "论述一碳单位来源、载体、形式与生理意义；常和叶酸、B₁₂及核苷酸合成串联。",
  },
  {
    ...shared, id: "gs-gogat", label: "GS–GOGAT", short: "GS/GOGAT", x: 34, y: 68, size: 72, subject: "biochem", priority: 2, mode: "nitrogen", source: "河南农课件",
    summary: "植物和微生物同化氨的高亲和主通路：GS 先生成谷氨酰胺，GOGAT 再把酰胺氮转给 α-酮戊二酸形成谷氨酸。",
    location: "植物叶绿体/质体及细胞质同工酶系统",
    equation: "Glu + NH₄⁺ + ATP → Gln；Gln + α-KG + 还原力 → 2 Glu",
    enzymes: [{ name: "谷氨酰胺合成酶", note: "消耗 ATP 固定游离氨", type: "氨同化" }, { name: "谷氨酸合成酶", note: "又称 GOGAT，把谷氨酰胺氮转至 α-KG", type: "还原氨化" }],
    flags: ["农业特色", "氨同化", "耗ATP", "植物/微生物"],
    exam: "河南农资料出现较少但属农业特色补充：与 GDH 途径比较亲和力、能量与生理场景。",
  },
  {
    ...shared, id: "prpp", label: "PRPP", short: "PRPP", x: 12, y: 78, size: 56, subject: "biochem", priority: 3, mode: "nitrogen", source: "河南农资料高频",
    summary: "活化的核糖-5-磷酸，既为嘌呤从头合成提供糖骨架，也参与嘧啶接糖与嘌呤补救合成。",
    location: "胞质；由磷酸戊糖途径提供核糖-5-磷酸",
    equation: "核糖-5-P + ATP → PRPP + AMP",
    enzymes: [{ name: "PRPP 合成酶", note: "消耗 ATP 的焦磷酸基，生成高反应性 PRPP", type: "活化核糖" }],
    flags: ["连接PPP", "嘌呤从头", "嘧啶接糖", "补救途径"],
    exam: "追踪 PPP 如何向核苷酸合成供碳，并比较从头合成与补救合成。",
  },
  {
    ...shared, id: "purine", label: "嘌呤核苷酸合成", short: "PURINE", x: 28, y: 88, size: 69, subject: "biochem", priority: 3, mode: "nitrogen", source: "河南农资料高频",
    summary: "嘌呤环逐步装配在 PRPP 上，先生成 IMP，再分支为 AMP 与 GMP；分支互相消耗对方核苷三磷酸以平衡供给。",
    location: "胞质从头合成；补救途径回收游离碱基",
    equation: "PRPP + Gln + Gly + Asp + CO₂ + 2×10-formyl-THF → IMP → AMP/GMP",
    enzymes: [{ name: "谷氨酰胺-PRPP酰胺转移酶", note: "承诺/限速步骤，受 AMP、GMP、IMP 反馈抑制", type: "限速酶" }],
    flags: ["先IMP", "环建在PRPP上", "反馈抑制", "补救途径"],
    exam: "比较嘌呤与嘧啶从头合成时‘先成环还是先接糖’，并写 IMP 分支调节。",
  },
  {
    ...shared, id: "pyrimidine", label: "嘧啶核苷酸合成", short: "PYR", x: 50, y: 85, size: 69, subject: "biochem", priority: 3, mode: "nitrogen", source: "河南农资料高频",
    summary: "先由氨甲酰磷酸与天冬氨酸构建嘧啶环生成乳清酸，再接到 PRPP 上形成 OMP/UMP。",
    location: "主要在胞质；真核二氢乳清酸脱氢酶位于线粒体内膜",
    equation: "Gln + CO₂ + ATP + Asp → 乳清酸 → OMP → UMP → CTP",
    enzymes: [{ name: "CPS-II", note: "胞质、以谷氨酰胺为氮源；受 UTP 抑制、PRPP/ATP 激活", type: "限速酶" }],
    flags: ["先成环后接糖", "CPS-II", "UMP", "反馈调节"],
    exam: "与嘌呤合成、尿素循环 CPS-I 进行三方比较。",
  },
  {
    ...shared, id: "rnr", label: "核糖核苷酸还原酶", short: "RNR", x: 72, y: 89, size: 62, subject: "biochem", priority: 3, mode: "nitrogen", source: "河南农课件",
    summary: "把 NDP 还原为 dNDP，为 DNA 合成统一提供脱氧核苷酸；通过复杂别构位点维持四种 dNTP 平衡。",
    location: "胞质；还原力最终来自 NADPH，经硫氧还蛋白/谷氧还蛋白传递",
    equation: "NDP + 还原型硫氧还蛋白 → dNDP + H₂O",
    enzymes: [{ name: "胸苷酸合成酶", note: "dUMP + 亚甲基-THF → dTMP；叶酸循环提供一碳单位", type: "dTMP合成" }],
    flags: ["DNA前体", "NADPH间接供电子", "别构调节", "dNTP平衡"],
    exam: "把 PPP→NADPH、叶酸一碳单位、RNR 与 dTMP 合成连成核苷酸串联题。",
  },
  {
    ...shared, id: "tca", label: "三羧酸循环", short: "TCA", x: 70, y: 47, size: 88, subject: "cross", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "糖、脂肪和氨基酸分解的共同枢纽。每轮把 1 个乙酰基氧化为 2 CO₂，并把还原力交给呼吸链。",
    location: "真核细胞：线粒体基质；琥珀酸脱氢酶位于内膜",
    equation: "乙酰-CoA + 3 NAD⁺ + FAD + GDP + Pi → 2 CO₂ + 3 NADH + FADH₂ + GTP",
    enzymes: [
      { name: "异柠檬酸脱氢酶", note: "主要限速点；生成 NADH 与 CO₂", type: "氧化脱羧" },
      { name: "α-酮戊二酸脱氢酶复合体", note: "需 TPP、硫辛酸、FAD、NAD⁺、CoA", type: "氧化脱羧" },
      { name: "琥珀酰-CoA 合成酶", note: "循环中唯一直接生成 GTP 的一步", type: "底物水平磷酸化" },
    ],
    flags: ["3 NADH", "1 FADH₂", "2 次脱羧", "1 GTP", "两用代谢途径"],
    exam: "论述 TCA 的反应历程、能量收支、调控及其为何是三大营养物代谢的共同枢纽。",
    crossLinks: [
      { id: "ppp", question: "比较两条通路的碳流、还原力与功能；说明 PPP 如何经 F6P/G3P 接入糖酵解，再进入 TCA。" },
      { id: "glyoxylate", question: "为什么萌发种子需要乙醛酸循环？从‘保碳’角度解释与 TCA 的分流。" },
      { id: "mitochondria", question: "把 TCA 的酶定位、呼吸链、质子梯度与 ATP 合成串成完整论述。" },
    ],
  },
  {
    ...shared, id: "glycolysis", label: "糖酵解", short: "EMP", x: 29, y: 41, size: 78, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "葡萄糖在胞质中变为 2 分子丙酮酸；净得 2 ATP 与 2 NADH，是有氧和无氧代谢的共同起点。",
    location: "胞质溶胶",
    equation: "葡萄糖 + 2 ADP + 2 Pi + 2 NAD⁺ → 2 丙酮酸 + 2 ATP + 2 NADH",
    enzymes: [
      { name: "己糖激酶 / 葡萄糖激酶", note: "第 1 个不可逆步骤；消耗 ATP", type: "磷酸化" },
      { name: "磷酸果糖激酶-1", note: "最主要限速酶；受 ATP、AMP、柠檬酸等调节", type: "限速步骤" },
      { name: "丙酮酸激酶", note: "PEP 向 ADP 转移磷酸基；生成 ATP", type: "底物水平磷酸化" },
    ],
    flags: ["净得 2 ATP", "2 NADH", "2 次底物水平磷酸化", "3 个不可逆步骤"],
    exam: "写出不可逆步骤并比较糖酵解与糖异生的绕行反应；常与能量收支计算合并考查。",
    crossLinks: [{ id: "ppp", question: "当细胞更需要 NADPH 或核糖-5-磷酸时，葡萄糖-6-磷酸如何在两条通路间分流？" }],
  },
  {
    ...shared, id: "ppp", label: "磷酸戊糖途径", short: "PPP", x: 14, y: 64, size: 76, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "不直接产 ATP，核心产物是 NADPH 与核糖-5-磷酸；非氧化阶段可把碳骨架送回糖酵解。",
    location: "胞质溶胶；脂肪合成活跃组织、红细胞等较旺盛",
    equation: "G6P + 2 NADP⁺ + H₂O → 核酮糖-5-P + 2 NADPH + CO₂",
    enzymes: [
      { name: "葡萄糖-6-磷酸脱氢酶（G6PD）", note: "氧化阶段限速酶；受 NADP⁺/NADPH 比调节", type: "脱氢反应" },
      { name: "转酮醇酶", note: "需 TPP；转移二碳单位", type: "非氧化阶段" },
      { name: "转醛醇酶", note: "转移三碳单位", type: "非氧化阶段" },
    ],
    flags: ["生成 NADPH", "生成核糖-5-P", "不直接生成 ATP", "氧化阶段不可逆"],
    exam: "题型重点是生理意义、氧化/非氧化两阶段、NADPH 用途及与糖酵解的碳流互换。",
    crossLinks: [
      { id: "tca", question: "比较 PPP 与 TCA 的产物、功能和 CO₂ 来源；追踪 PPP 碳骨架如何进入 TCA。" },
      { id: "fatty-acid-synthesis", question: "脂肪酸合成为什么依赖 NADPH？列举另外两种 NADPH 来源或用途。" },
    ],
  },
  {
    ...shared, id: "g6p", label: "葡萄糖-6-磷酸", short: "G6P", x: 14, y: 22, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "糖代谢的十字路口：可进入糖酵解、磷酸戊糖途径、糖原/淀粉合成或经去磷酸化释放葡萄糖。",
    location: "胞质；植物叶绿体内也存在相应糖磷酸代谢",
    equation: "葡萄糖 + ATP → G6P + ADP",
    enzymes: [{ name: "己糖激酶", note: "捕获葡萄糖并维持跨膜浓度梯度", type: "不可逆磷酸化" }],
    flags: ["代谢分流点", "消耗 ATP", "带电不易出膜"],
    exam: "给定能量、NADPH 或核苷酸需求，判断 G6P 的主要去向并说明调节依据。",
  },
  {
    ...shared, id: "g6pd", label: "G6P脱氢酶", short: "G6PD", x: 5, y: 45, size: 54, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "磷酸戊糖途径氧化阶段的限速酶，决定 NADPH 供给能力。",
    location: "胞质溶胶",
    equation: "G6P + NADP⁺ → 6-磷酸葡糖酸内酯 + NADPH + H⁺",
    enzymes: [{ name: "G6PD", note: "NADPH 反馈抑制，NADP⁺促进", type: "限速脱氢" }],
    flags: ["限速酶", "NADPH", "氧化阶段"],
    exam: "解释 G6PD 活性下降为何会削弱细胞应对氧化胁迫的能力。",
  },
  {
    ...shared, id: "nadph", label: "NADPH", short: "NADPH", x: 7, y: 84, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "还原性合成与抗氧化体系的“电子货币”，不同于主要把电子送去产 ATP 的 NADH。",
    location: "主要在胞质/叶绿体中用于还原反应",
    equation: "NADP⁺ + 2e⁻ + H⁺ ⇌ NADPH",
    enzymes: [{ name: "谷胱甘肽还原酶", note: "用 NADPH 再生 GSH，维持抗氧化状态", type: "还原反应" }],
    flags: ["脂肪酸合成", "抗氧化", "P450", "光合作用"],
    exam: "比较 NADPH 与 NADH 的来源、用途及细胞区室分工。",
  },
  {
    ...shared, id: "pep", label: "磷酸烯醇式丙酮酸", short: "PEP", x: 45, y: 19, subject: "biochem", priority: 3, mode: "metabolism", source: "教材主线",
    summary: "具有高磷酸基团转移势能，是糖酵解末端直接生成 ATP 的高能中间物。",
    location: "胞质溶胶",
    equation: "PEP + ADP + H⁺ → 丙酮酸 + ATP",
    enzymes: [{ name: "丙酮酸激酶", note: "糖酵解第 3 个不可逆步骤", type: "底物水平磷酸化" }],
    flags: ["高能磷酸化合物", "生成 ATP", "不可逆"],
    exam: "说明 PEP 水解为何具有较大自由能变化，并联系底物水平磷酸化。",
  },
  {
    ...shared, id: "pyruvate", label: "丙酮酸", short: "Pyruvate", x: 48, y: 43, size: 68, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "糖酵解终产物，也是乳酸/乙醇发酵、糖异生、乙酰-CoA 和多种氨基酸代谢的分流点。",
    location: "胞质生成；经转运进入线粒体",
    equation: "丙酮酸 + CoA + NAD⁺ → 乙酰-CoA + CO₂ + NADH",
    enzymes: [{ name: "丙酮酸脱氢酶复合体", note: "E1/E2/E3 与 5 种辅酶协同；不可逆", type: "氧化脱羧" }],
    flags: ["代谢枢纽", "连接糖酵解与 TCA", "不可逆"],
    exam: "常考 PDH 复合体组成、辅酶、调节，以及丙酮酸的四种主要去路。",
  },
  {
    ...shared, id: "acetyl", label: "乙酰辅酶A", short: "Acetyl-CoA", x: 62, y: 22, size: 68, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "活化乙酰基载体：进入 TCA，也参与脂肪酸、酮体、胆固醇等合成。",
    location: "线粒体基质与胞质池彼此分隔；柠檬酸穿梭可转移乙酰基",
    equation: "乙酰-CoA + 草酰乙酸 + H₂O → 柠檬酸 + CoA-SH",
    enzymes: [{ name: "柠檬酸合酶", note: "TCA 第一步；受 ATP、NADH、柠檬酸等抑制", type: "缩合" }],
    flags: ["高能硫酯键", "糖脂交汇", "不能净生糖（动物）"],
    exam: "解释脂肪酸分解产生的乙酰-CoA 为何在动物体内不能净转变为葡萄糖。",
  },
  {
    ...shared, id: "oaa", label: "草酰乙酸", short: "OAA", x: 62, y: 75, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "TCA 的受体与再生物，同时连接糖异生、天冬氨酸代谢和苹果酸穿梭。",
    location: "线粒体基质；不能直接跨内膜",
    equation: "丙酮酸 + CO₂ + ATP → 草酰乙酸 + ADP + Pi",
    enzymes: [{ name: "丙酮酸羧化酶", note: "需生物素；乙酰-CoA 激活；补充 TCA 中间物", type: "回补反应" }],
    flags: ["回补反应", "糖异生", "需生物素"],
    exam: "从草酰乙酸浓度解释饥饿时乙酰-CoA 转向酮体合成的原因。",
  },
  {
    ...shared, id: "beta-oxidation", label: "脂肪酸β氧化", short: "β-OX", x: 43, y: 80, size: 72, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "脂酰-CoA 反复经历脱氢、水合、再脱氢、硫解，每轮切下 1 个乙酰-CoA。",
    location: "真核主要在线粒体基质；超长链脂肪酸先在过氧化物酶体",
    equation: "脂酰-CoA(n) → 脂酰-CoA(n−2) + 乙酰-CoA + FADH₂ + NADH",
    enzymes: [
      { name: "肉碱脂酰转移酶Ⅰ（CPT-I）", note: "长链脂酰基进入线粒体的控制点；受丙二酰-CoA抑制", type: "限速转运" },
      { name: "脂酰-CoA 脱氢酶", note: "第一步脱氢，电子经 ETF 入呼吸链", type: "脱氢" },
    ],
    flags: ["4 步循环", "NADH", "FADH₂", "乙酰-CoA"],
    exam: "计算饱和偶数碳脂肪酸完全氧化的 ATP，并说明活化成本与旧版/新版 P/O 比差异。",
  },
  {
    ...shared, id: "fatty-acid-synthesis", label: "脂肪酸合成", short: "FA SYN", x: 25, y: 82, size: 66, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "以乙酰-CoA 为引物、丙二酰-CoA 为二碳供体，消耗 NADPH 在胞质合成长链脂肪酸。",
    location: "动物/真菌胞质；植物脂肪酸从头合成主要在质体",
    equation: "乙酰-CoA + 7 丙二酰-CoA + 14 NADPH → 棕榈酸 + 7 CO₂ + 14 NADP⁺",
    enzymes: [{ name: "乙酰-CoA 羧化酶（ACC）", note: "限速酶；需生物素；生成丙二酰-CoA", type: "限速羧化" }],
    flags: ["消耗 NADPH", "ACC 限速", "ACP 载体", "与β氧化分区"],
    exam: "对照脂肪酸合成与 β 氧化的区室、载体、二碳单位、辅酶与调节。",
  },
  {
    ...shared, id: "glyoxylate", label: "乙醛酸循环", short: "GLX", x: 22, y: 58, size: 68, subject: "cross", priority: 3, mode: "metabolism", source: "同类农校预测",
    summary: "绕过 TCA 两个脱羧步骤，使乙酰-CoA 的碳得以净转为四碳酸；对油料种子萌发尤重要。",
    location: "植物乙醛酸循环体（特化过氧化物酶体）与线粒体协作",
    equation: "2 乙酰-CoA → 琥珀酸 + 2 CoA-SH（碳骨架净保留）",
    enzymes: [
      { name: "异柠檬酸裂解酶", note: "异柠檬酸裂解为琥珀酸与乙醛酸", type: "特征酶" },
      { name: "苹果酸合酶", note: "乙醛酸与乙酰-CoA 缩合为苹果酸", type: "特征酶" },
    ],
    flags: ["植物高频", "保碳", "油料种子萌发", "两种特征酶"],
    exam: "农业院校偏好题：比较乙醛酸循环与 TCA，解释脂肪如何在植物中转为糖。",
    crossLinks: [{ id: "tca", question: "画出分叉与汇合点，并解释绕过两个脱羧步骤带来的生理意义。" }],
  },
  {
    ...shared, id: "nadh", label: "NADH", short: "NADH", x: 86, y: 18, subject: "biochem", priority: 3, mode: "metabolism", source: "教材主线",
    summary: "分解代谢产生的主要还原当量，把高能电子交给呼吸链复合体Ⅰ。",
    location: "胞质与线粒体池分隔；依靠穿梭转移还原当量",
    equation: "NADH → NAD⁺ + H⁺ + 2e⁻",
    enzymes: [{ name: "NADH 脱氢酶（复合体Ⅰ）", note: "接收 NADH 电子并泵出质子", type: "氧化还原" }],
    flags: ["复合体Ⅰ供电子", "约 2.5 ATP / NADH", "穿梭系统"],
    exam: "比较苹果酸-天冬氨酸穿梭与甘油-3-磷酸穿梭对 ATP 收支的影响。",
  },
  {
    ...shared, id: "etc", label: "电子传递链", short: "ETC", x: 91, y: 48, size: 75, subject: "cross", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "复合体Ⅰ—Ⅳ按氧化还原电势递增传递电子，并由Ⅰ、Ⅲ、Ⅳ泵质子建立电化学梯度。",
    location: "线粒体内膜；植物还具有替代氧化酶支路",
    equation: "NADH + H⁺ + 1/2 O₂ → NAD⁺ + H₂O（耦联质子泵出）",
    enzymes: [
      { name: "复合体Ⅰ", note: "NADH → Q；泵质子", type: "NADH 脱氢酶" },
      { name: "复合体Ⅱ", note: "琥珀酸 → Q；不泵质子", type: "琥珀酸脱氢酶" },
      { name: "复合体Ⅳ", note: "细胞色素 c → O₂；生成水并泵质子", type: "末端氧化酶" },
    ],
    flags: ["ⅠⅢⅣ泵质子", "O₂末端受体", "化学渗透", "抑制剂高频"],
    exam: "给出抑制剂或解偶联剂，判断电子流、耗氧、质子梯度、ATP 合成与产热的变化。",
    crossLinks: [{ id: "mitochondria", question: "从内膜结构、呼吸链方向与 ATP 合酶朝向解释氧化磷酸化。" }],
  },
  {
    ...shared, id: "atp-synthase", label: "ATP合酶", short: "F₀F₁", x: 88, y: 82, size: 68, subject: "cross", priority: 3, mode: "metabolism", source: "河南农既有大纲",
    summary: "F₀ 传导质子并驱动转子，F₁ 通过结合变构机制催化 ADP 与 Pi 生成 ATP。",
    location: "线粒体内膜；F₁ 头部朝基质侧",
    equation: "ADP + Pi + 质子驱动力 → ATP + H₂O",
    enzymes: [{ name: "F₀F₁-ATP 合酶", note: "旋转催化；可被寡霉素抑制", type: "氧化磷酸化" }],
    flags: ["质子动力势", "旋转催化", "结合变构", "不是底物水平磷酸化"],
    exam: "区分氧化磷酸化与底物水平磷酸化，并解释解偶联为什么增加耗氧却减少 ATP。",
  },
  {
    ...shared, id: "gluconeogenesis", label: "糖异生", short: "GNG", x: 37, y: 58, size: 67, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农资料高频",
    summary: "由乳酸、甘油和生糖氨基酸等非糖物质合成葡萄糖，不是糖酵解的简单逆转，而是绕过三个不可逆步骤。",
    location: "肝/肾；反应跨线粒体、胞质和内质网",
    equation: "2 丙酮酸 + 4 ATP + 2 GTP + 2 NADH → 葡萄糖 + 4 ADP + 2 GDP + 6 Pi",
    enzymes: [{ name: "丙酮酸羧化酶", note: "线粒体、需生物素，乙酰-CoA 激活", type: "绕行1" }, { name: "果糖-1,6-二磷酸酶", note: "主要调控点，受 AMP 与 F-2,6-BP 抑制", type: "限速步骤" }],
    flags: ["4 ATP + 2 GTP", "三处绕行", "乳酸循环", "与糖酵解互调"],
    exam: "比较糖酵解与糖异生的不可逆步骤、调节和区室；结合 Cori 循环解释组织分工。",
    crossLinks: [{ id: "glycolysis", question: "逐一配对三个不可逆步骤及其绕行酶，说明如何避免无效循环。" }],
  },
  {
    ...shared, id: "glycogen-starch", label: "糖原与淀粉代谢", short: "GLY/ST", x: 8, y: 8, size: 62, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农资料高频",
    summary: "动物糖原与植物淀粉都是葡萄糖储存形式；合成依赖活化糖核苷酸，分解多用磷酸解，支链形成与去除需专门酶。",
    location: "糖原在胞质颗粒；植物淀粉在质体",
    equation: "动物：UDP-Glc → 糖原；植物淀粉：ADP-Glc → 淀粉",
    enzymes: [{ name: "糖原磷酸化酶", note: "磷酸解 α-1,4 键，生成 G1P", type: "分解限速" }, { name: "糖原合酶", note: "以 UDP-Glc 延长非还原端", type: "合成限速" }],
    flags: ["活化糖", "非还原端", "磷酸解", "支链酶/去支链酶"],
    exam: "对比合成与分解的供体、关键酶和共价/激素调节；农业方向注意 UDPG 与 ADPG。",
  },
  {
    ...shared, id: "substrate-phosphorylation", label: "底物水平磷酸化", short: "SLP", x: 54, y: 6, size: 58, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农资料高频",
    summary: "高能底物把磷酸基直接转给 ADP/GDP，生成 ATP/GTP；不依赖膜、呼吸链和质子梯度。",
    location: "糖酵解胞质与 TCA 的线粒体基质",
    equation: "1,3-BPG→3-PG；PEP→丙酮酸；琥珀酰-CoA→琥珀酸",
    enzymes: [{ name: "磷酸甘油酸激酶 / 丙酮酸激酶", note: "糖酵解两处 ATP 生成", type: "直接转磷酸" }, { name: "琥珀酰-CoA合成酶", note: "TCA 生成 GTP/ATP", type: "硫酯能量耦联" }],
    flags: ["不需氧", "不需膜", "三类典型反应", "与氧化磷酸化对比"],
    exam: "列出生物体内典型底物水平磷酸化步骤，并与氧化磷酸化比较能量来源。",
  },
  {
    ...shared, id: "malate-shuttle", label: "苹果酸-天冬氨酸穿梭", short: "MAS", x: 76, y: 8, size: 59, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农资料高频",
    summary: "把胞质 NADH 的还原当量等价转入线粒体 NADH 池，同时交换苹果酸、α-酮戊二酸、天冬氨酸与谷氨酸。",
    location: "胞质—线粒体内膜—基质协作",
    equation: "胞质 NADH → 基质 NADH（约按 2.5 ATP/NADH 计）",
    enzymes: [{ name: "苹果酸脱氢酶", note: "胞质还原 OAA、基质再氧化苹果酸", type: "可逆脱氢" }, { name: "天冬氨酸转氨酶", note: "解决 OAA 不能直接跨膜的问题", type: "转氨" }],
    flags: ["还原当量", "不搬运NADH本身", "约2.5 ATP", "跨膜载体"],
    exam: "与甘油-3-磷酸穿梭比较电子入口和 ATP 收益；强调搬运的是还原当量。",
  },
  {
    ...shared, id: "uncoupling", label: "抑制剂与解偶联", short: "BLOCK/UNC", x: 96, y: 67, size: 57, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农资料高频",
    summary: "呼吸链抑制剂阻断电子流；ATP 合酶抑制剂阻止质子回流；解偶联剂耗散梯度，使耗氧可继续/加快而 ATP 下降、产热增加。",
    location: "线粒体内膜氧化磷酸化系统",
    equation: "解偶联：电子传递↑/可进行，Δp↓，ATP↓，耗氧↑，产热↑",
    enzymes: [{ name: "鱼藤酮 / 抗霉素A / 氰化物", note: "分别抑制复合体 I、III、IV", type: "呼吸链抑制" }, { name: "寡霉素", note: "阻断 F₀ 质子通道，抑制 ATP 合酶", type: "磷酸化抑制" }],
    flags: ["给药判断题", "耗氧变化", "梯度变化", "ATP/产热"],
    exam: "用四列依次判断电子流、耗氧、质子梯度、ATP；不要把抑制剂与解偶联剂混写。",
  },
  {
    ...shared, id: "ketone-body", label: "酮体", short: "KETONE", x: 78, y: 93, size: 59, subject: "biochem", priority: 3, mode: "metabolism", source: "河南农资料高频",
    summary: "肝线粒体在脂肪酸分解旺盛而草酰乙酸偏向糖异生时，把乙酰-CoA 转为可溶性燃料输出；肝自身不能利用。",
    location: "肝线粒体合成；肝外组织线粒体利用",
    equation: "2 乙酰-CoA → 乙酰乙酸 ↔ β-羟丁酸 / 丙酮",
    enzymes: [{ name: "HMG-CoA合酶", note: "肝酮体生成关键酶", type: "酮体合成" }, { name: "硫解酶/SCOT", note: "肝外利用酮体；肝缺 SCOT", type: "酮体利用" }],
    flags: ["肝生肝不用", "饥饿/糖尿病", "乙酰-CoA", "酸中毒"],
    exam: "从 OAA、糖异生与 β 氧化解释酮体增加，比较生成与利用组织。",
  },
  {
    ...shared, id: "cholesterol", label: "胆固醇", short: "CHOL", x: 57, y: 94, size: 57, subject: "biochem", priority: 2, mode: "metabolism", source: "河南农资料高频",
    summary: "来源于膳食与乙酰-CoA 从头合成；去路包括膜成分、胆汁酸、类固醇激素和维生素 D，不能彻底氧化供能。",
    location: "胞质/光面 ER 合成；肝是代谢与脂蛋白运输枢纽",
    equation: "乙酰-CoA → HMG-CoA → 甲羟戊酸 → 胆固醇",
    enzymes: [{ name: "HMG-CoA还原酶", note: "合成限速酶，受胆固醇反馈、磷酸化和转录调节", type: "限速酶" }],
    flags: ["来源与去路", "HMG-CoA还原酶", "膜流动性", "胆汁酸/激素"],
    exam: "资料中的期末大题覆盖其来源与去路；回答按外源、内源、转化、排泄分层。",
  },

  {
    ...shared, id: "membrane", label: "生物膜", short: "MEM", x: 49, y: 43, size: 86, subject: "cell", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "流动镶嵌的选择性屏障，也是物质运输、能量转换、信号转导与细胞识别的平台。",
    location: "质膜及各种内膜系统",
    equation: "结构主线：脂双层 + 膜蛋白 + 糖链；功能来自不对称性、流动性与区室化",
    enzymes: [{ name: "膜蛋白", note: "跨膜、脂锚定或外周结合；承担运输、受体、酶等功能", type: "结构—功能" }],
    flags: ["流动镶嵌模型", "膜不对称性", "膜流动性", "选择透过性"],
    exam: "从脂质组成、温度与胆固醇解释膜流动性变化；结合 FRAP 实验分析膜蛋白运动。",
    crossLinks: [{ id: "etc", question: "为什么呼吸链必须位于连续且低质子通透性的线粒体内膜上？" }],
  },
  {
    ...shared, id: "phospholipid", label: "磷脂", short: "PL", x: 23, y: 18, subject: "cross", priority: 3, mode: "cell", source: "教材主线",
    summary: "两亲性分子自组装成脂双层；不同头基和脂肪酸尾决定膜曲率、流动性与信号功能。",
    location: "膜脂双层；不同膜与双层两侧分布不对称",
    equation: "亲水头部朝向水相，疏水尾部相对形成膜芯",
    enzymes: [{ name: "翻转酶 / 扰乱酶", note: "维持或改变膜脂不对称性", type: "跨层转位" }],
    flags: ["两亲性", "自组装", "侧向扩散", "不对称"],
    exam: "说明磷脂酰丝氨酸外翻如何成为细胞凋亡识别信号。",
  },
  {
    ...shared, id: "transport", label: "膜运输", short: "TRANS", x: 71, y: 18, size: 67, subject: "cell", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "包括简单扩散、易化扩散、主动运输与囊泡运输；判断关键是能量、梯度和载体。",
    location: "质膜与细胞器膜",
    equation: "电化学势 = 浓度梯度项 + 电势梯度项",
    enzymes: [{ name: "Na⁺/K⁺-ATPase", note: "每水解 1 ATP：3 Na⁺ 出、2 K⁺ 入；原发主动运输", type: "P型泵" }],
    flags: ["主动/被动", "原发/继发", "载体饱和性", "电化学梯度"],
    exam: "用实例区分通道、载体、泵和协同运输，并判断抑制 ATP 供应后的变化。",
  },
  {
    ...shared, id: "mitochondria", label: "线粒体", short: "MITO", x: 23, y: 47, size: 78, subject: "cross", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "双层膜半自主细胞器；基质进行 TCA，内膜进行电子传递与氧化磷酸化，也参与凋亡。",
    location: "外膜—膜间隙—内膜/嵴—基质四级区室",
    equation: "区室化主线：基质产 NADH → 内膜泵 H⁺ → 膜间隙积累 → ATP 合酶回流",
    enzymes: [{ name: "细胞色素 c", note: "呼吸链电子载体；释放到胞质后参与凋亡小体形成", type: "双重角色" }],
    flags: ["双层膜", "半自主", "母系遗传", "能量+凋亡"],
    exam: "比较线粒体与叶绿体的结构、基因组、蛋白导入和能量转换机制。",
    crossLinks: [
      { id: "tca", question: "把 TCA、呼吸链和 ATP 合成按线粒体区室完整串联。" },
      { id: "apoptosis", question: "说明线粒体外膜通透化如何把代谢细胞器变成凋亡信号平台。" },
    ],
  },
  {
    ...shared, id: "chloroplast", label: "叶绿体", short: "CHL", x: 8, y: 29, size: 70, subject: "cross", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "植物特有的双层膜半自主细胞器；类囊体膜进行光反应，基质进行 Calvin 循环。",
    location: "外/内包膜、基质、类囊体膜与腔",
    equation: "光能 → ATP + NADPH；CO₂ + ATP + NADPH → 三碳糖",
    enzymes: [{ name: "Rubisco", note: "羧化与加氧双功能；连接 Calvin 循环与光呼吸", type: "关键酶" }],
    flags: ["植物重点", "类囊体", "Calvin 循环", "半自主"],
    exam: "农业院校倾向：比较叶绿体与线粒体的质子梯度方向、ATP 合酶朝向和碳代谢功能。",
  },
  {
    ...shared, id: "er", label: "内质网", short: "ER", x: 18, y: 75, size: 68, subject: "cell", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "粗面内质网负责分泌/膜/溶酶体蛋白共翻译转位，光面内质网参与脂质合成、解毒和 Ca²⁺ 储存。",
    location: "与核外膜连续的内膜网络",
    equation: "信号肽—SRP—SRP受体—转位子：将翻译导向 ER",
    enzymes: [{ name: "信号肽酶 / 蛋白二硫键异构酶", note: "切除信号肽并辅助腔内蛋白折叠", type: "加工与质控" }],
    flags: ["共翻译转位", "蛋白质折叠", "脂质合成", "UPR"],
    exam: "从信号肽开始，追踪一个分泌蛋白到胞外的全过程。",
  },
  {
    ...shared, id: "golgi", label: "高尔基体", short: "GOLGI", x: 42, y: 78, size: 66, subject: "cell", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "对来自 ER 的蛋白和脂质进行修饰、分选与包装，具有顺面—中间—反面极性。",
    location: "顺面靠 ER，反面高尔基网负责分选",
    equation: "ER → COPⅡ → Golgi；Golgi → COPⅠ → ER；TGN → 目的地",
    enzymes: [{ name: "糖基转移酶", note: "分区定位，逐步加工 N-连接和 O-连接糖链", type: "蛋白修饰" }],
    flags: ["顺反极性", "糖基化", "膜泡分选", "M6P"],
    exam: "比较 COPⅠ、COPⅡ 与网格蛋白包被小泡的方向、货物与发生部位。",
  },
  {
    ...shared, id: "lysosome", label: "溶酶体", short: "LYSO", x: 63, y: 79, size: 64, subject: "cell", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "酸性水解细胞器，通过异噬、自噬和内吞途径降解大分子并回收单体。",
    location: "动物细胞内；腔内 pH 约 4.5–5.0",
    equation: "V型 H⁺-ATPase 消耗 ATP 将 H⁺ 泵入腔内",
    enzymes: [{ name: "酸性水解酶", note: "M6P 标记经受体从 TGN 运送至内体/溶酶体", type: "降解" }],
    flags: ["酸性腔室", "M6P分选", "自噬", "异噬"],
    exam: "说明溶酶体酶误分泌的分选机制缺陷，并联系 I-cell 病的原理。",
  },
  {
    ...shared, id: "peroxisome", label: "过氧化物酶体", short: "PEROX", x: 87, y: 77, size: 66, subject: "cross", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "单层膜氧化细胞器；进行超长链脂肪酸氧化并以过氧化氢酶清除 H₂O₂；植物还参与光呼吸。",
    location: "胞质内单层膜细胞器；蛋白质翻译后导入",
    equation: "2 H₂O₂ → 2 H₂O + O₂",
    enzymes: [{ name: "过氧化氢酶", note: "高效分解 H₂O₂，保护细胞免受氧化损伤", type: "抗氧化" }],
    flags: ["单层膜", "无自身DNA", "VLCFA氧化", "植物光呼吸"],
    exam: "比较过氧化物酶体与线粒体 β 氧化的电子去向、能量保留和底物偏好。",
  },
  {
    ...shared, id: "cytoskeleton", label: "细胞骨架", short: "CYTO", x: 72, y: 48, size: 74, subject: "cell", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "微丝、微管和中间丝构成动态支架，负责形态、运动、运输、分裂与力学稳定。",
    location: "贯穿胞质并与膜、细胞器、细胞连接耦联",
    equation: "结构—马达对应：微丝↔肌球蛋白；微管↔驱动蛋白/动力蛋白",
    enzymes: [{ name: "GTP/ATP 水解", note: "微管动态不稳定性依赖 GTP；肌动蛋白动态依赖 ATP", type: "动态装配" }],
    flags: ["微丝", "微管", "中间丝", "马达蛋白"],
    exam: "比较三类骨架的单体、极性、直径、马达蛋白、抑制剂与主要功能。",
  },
  {
    ...shared, id: "microtubule", label: "微管", short: "MT", x: 90, y: 28, subject: "cell", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "由 α/β 微管蛋白异二聚体组成的极性中空管，具有动态不稳定性，形成纺锤体、纤毛和运输轨道。",
    location: "从微管组织中心向细胞周边辐射",
    equation: "GTP帽稳定增长端；GTP水解后帽丢失可触发灾变",
    enzymes: [{ name: "驱动蛋白 / 动力蛋白", note: "通常分别向 + 端 / − 端运输", type: "马达蛋白" }],
    flags: ["13根原纤维", "动态不稳定", "GTP帽", "有丝分裂"],
    exam: "用动态不稳定性解释秋水仙素、紫杉醇对纺锤体和细胞分裂的影响。",
  },
  {
    ...shared, id: "actin", label: "肌动蛋白", short: "ACTIN", x: 91, y: 53, subject: "cell", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "G-肌动蛋白聚合为有极性的 F-肌动蛋白，参与细胞皮层、收缩环、伪足与肌肉收缩。",
    location: "细胞皮层丰富，也形成应力纤维和收缩环",
    equation: "ATP-G-actin → F-actin；踏车行为依赖两端临界浓度差异",
    enzymes: [{ name: "肌球蛋白", note: "沿微丝运动并水解 ATP", type: "马达蛋白" }],
    flags: ["踏车行为", "细胞质分裂", "细胞迁移", "微绒毛"],
    exam: "比较微丝踏车行为与微管动态不稳定性的分子基础。",
  },
  {
    ...shared, id: "cell-cycle", label: "细胞周期", short: "CYCLE", x: 50, y: 61, size: 72, subject: "cell", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "G₁—S—G₂—M 的有序推进由 Cyclin-CDK 脉冲与检查点共同保证。",
    location: "核与胞质调控网络；有丝分裂涉及染色体、纺锤体和胞质分裂",
    equation: "Cyclin 周期性合成/降解 + CDK 磷酸化开关 → 单向周期转换",
    enzymes: [{ name: "Cyclin-CDK", note: "被 Wee1 抑制性磷酸化、Cdc25 去磷酸化激活", type: "蛋白激酶" }, { name: "APC/C", note: "泛素化 securin 和 M-cyclin，触发后期与退出 M 期", type: "E3泛素连接酶" }],
    flags: ["G1/S检查点", "G2/M检查点", "纺锤体检查点", "不可逆转换"],
    exam: "以 MPF 与 APC/C 为主线解释细胞如何进入和退出 M 期。",
  },
  {
    ...shared, id: "apoptosis", label: "细胞凋亡", short: "APOP", x: 73, y: 68, size: 68, subject: "cross", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "受控细胞死亡，由 initiator caspase 激活 executioner caspase；内源途径以线粒体为枢纽。",
    location: "胞质 caspase 级联；线粒体外膜通透化是内源途径关键点",
    equation: "Cytochrome c + Apaf-1 + procaspase-9 → 凋亡小体 → caspase-3",
    enzymes: [{ name: "Caspase", note: "切割 Asp 后肽键；以酶原形式存在并级联放大", type: "半胱氨酸蛋白酶" }],
    flags: ["程序性死亡", "caspase级联", "Bcl-2家族", "无炎症"],
    exam: "比较内源与外源凋亡途径的启动信号、复合体、起始 caspase 与汇合点。",
    crossLinks: [{ id: "mitochondria", question: "Bcl-2 家族如何控制线粒体外膜通透化与细胞色素 c 释放？" }],
  },
  {
    ...shared, id: "vacuole", label: "液泡", short: "VAC", x: 8, y: 56, subject: "cell", priority: 2, mode: "cell", source: "同类农校预测",
    summary: "植物细胞的重要区室，维持膨压、储存离子/代谢物、调节 pH，并兼具溶酶体样降解功能。",
    location: "成熟植物细胞中央液泡；液泡膜称 tonoplast",
    equation: "V型 H⁺-ATPase / H⁺-PPase 建立跨液泡膜质子梯度",
    enzymes: [{ name: "H⁺-PPase", note: "利用焦磷酸泵质子，是植物液泡的特色泵", type: "质子泵" }],
    flags: ["植物重点", "维持膨压", "储存", "降解"],
    exam: "说明液泡如何通过质子泵与次级主动运输积累离子和代谢物。",
  },
  {
    ...shared, id: "cell-wall", label: "植物细胞壁", short: "WALL", x: 32, y: 88, size: 66, subject: "cell", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "纤维素微纤丝嵌入半纤维素和果胶基质，提供机械支持、限制膨胀并参与细胞间通讯。",
    location: "质膜外；初生壁、次生壁与胞间层结构不同",
    equation: "纤维素合酶复合体沿皮层微管轨迹合成并排列纤维素微纤丝",
    enzymes: [{ name: "纤维素合酶", note: "质膜上的玫瑰花结复合体", type: "糖基转移酶" }],
    flags: ["植物重点", "纤维素", "胞间层", "胞间连丝"],
    exam: "从细胞壁组分、微管导向和膨压解释植物细胞定向生长。",
  },
  {
    ...shared, id: "signaling", label: "信号转导", short: "SIGNAL", x: 83, y: 45, size: 70, subject: "cross", priority: 3, mode: "cell", source: "同类农校预测",
    summary: "受体识别胞外信号，经第二信使与蛋白磷酸化级联放大、整合并终止响应。",
    location: "质膜、胞质与细胞核协同",
    equation: "信号 → 受体 → 转换/放大 → 效应器 → 细胞响应 → 终止",
    enzymes: [{ name: "蛋白激酶 / 磷酸酶", note: "可逆磷酸化构成大量信号开关", type: "共价修饰" }],
    flags: ["特异性", "放大", "整合", "脱敏"],
    exam: "以 GPCR-cAMP-PKA 为例画出从配体到基因表达的完整通路并说明关停机制。",
  },

  {
    ...shared, id: "dna", label: "DNA", short: "DNA", x: 48, y: 42, size: 86, subject: "cross", priority: 3, mode: "information", source: "河南农既有大纲",
    summary: "遗传信息载体。反向平行双螺旋、互补碱基配对和半保留复制共同保证稳定传递。",
    location: "真核主要在细胞核，线粒体与叶绿体也有基因组",
    equation: "5′-磷酸二酯键骨架；A=T（2个氢键），G≡C（3个氢键）",
    enzymes: [{ name: "拓扑异构酶", note: "切断并重接 DNA，改变超螺旋与连环状态", type: "DNA拓扑" }],
    flags: ["反向平行", "互补配对", "半保留复制", "超螺旋"],
    exam: "结合 Meselson-Stahl 实验解释半保留复制，并区分 Tm 与 GC 含量关系。",
  },
  {
    ...shared, id: "replication", label: "DNA复制", short: "REPL", x: 20, y: 25, size: 72, subject: "biochem", priority: 3, mode: "information", source: "河南农既有大纲",
    summary: "复制叉处双向、半不连续合成；所有 DNA 聚合酶只能按 5′→3′ 延伸并需要引物。",
    location: "真核 S 期细胞核；原核拟核区",
    equation: "(dNMP)n + dNTP → (dNMP)n+1 + PPi",
    enzymes: [{ name: "解旋酶", note: "解开双链；消耗 ATP", type: "复制叉" }, { name: "DNA聚合酶", note: "5′→3′合成；部分具有3′→5′校对", type: "聚合与校对" }, { name: "DNA连接酶", note: "连接冈崎片段间缺口", type: "磷酸二酯键形成" }],
    flags: ["半保留", "半不连续", "引物依赖", "5′→3′"],
    exam: "比较前导链与后随链，并按顺序写出复制叉各酶的作用。",
  },
  {
    ...shared, id: "dna-pol", label: "DNA聚合酶", short: "DNA POL", x: 7, y: 50, subject: "biochem", priority: 3, mode: "information", source: "河南农既有大纲",
    summary: "以模板链为指导，把 dNTP 加到引物 3′-OH；校对活性提高复制保真度。",
    location: "复制体核心组分",
    equation: "3′-OH 进攻 dNTP 的 α-磷酸，释放 PPi",
    enzymes: [{ name: "3′→5′外切酶", note: "移除错配核苷酸，承担校对", type: "校对" }],
    flags: ["模板依赖", "引物依赖", "5′→3′合成", "校对"],
    exam: "区分原核 DNA Pol I 与 Pol III，或真核 Pol α/δ/ε 的主要分工。",
  },
  {
    ...shared, id: "transcription", label: "转录", short: "TX", x: 31, y: 66, size: 68, subject: "biochem", priority: 3, mode: "information", source: "河南农既有大纲",
    summary: "RNA 聚合酶读取 DNA 模板链，合成与编码链同序（T换U）的 RNA；无需引物。",
    location: "真核细胞核；原核转录与翻译可偶联",
    equation: "DNA模板 + NTP → RNA + PPi（5′→3′）",
    enzymes: [{ name: "RNA聚合酶", note: "识别启动子、局部解链并催化 RNA 合成", type: "转录酶" }],
    flags: ["无需引物", "启动子", "模板链", "RNA加工"],
    exam: "比较原核与真核转录起始，并说明三种真核 RNA 聚合酶的主要产物。",
  },
  {
    ...shared, id: "rna-pol", label: "RNA聚合酶", short: "RNA POL", x: 13, y: 81, subject: "biochem", priority: 3, mode: "information", source: "河南农既有大纲",
    summary: "催化 NTP 聚合为 RNA；原核核心酶负责催化，σ 因子赋予启动子识别能力。",
    location: "转录泡中",
    equation: "核心酶 + σ因子 = 全酶（原核）",
    enzymes: [{ name: "RNA Pol II", note: "真核合成 mRNA；CTD 协调加帽、剪接和加尾", type: "真核转录" }],
    flags: ["σ因子", "启动子识别", "无需引物", "CTD"],
    exam: "解释 α-鹅膏蕈碱对不同真核 RNA 聚合酶的敏感性差异。",
  },
  {
    ...shared, id: "mrna", label: "mRNA", short: "mRNA", x: 53, y: 73, subject: "cross", priority: 3, mode: "information", source: "河南农既有大纲",
    summary: "把编码信息从 DNA 带到核糖体；真核前体需 5′加帽、剪接和 3′加 poly(A) 尾。",
    location: "核内加工，经核孔输出到胞质",
    equation: "pre-mRNA → 5′ cap + exon连接 + poly(A) → mature mRNA",
    enzymes: [{ name: "剪接体", note: "snRNP 识别剪接位点并通过两次转酯反应移除内含子", type: "RNA加工" }],
    flags: ["5′帽", "剪接", "poly(A)", "可变剪接"],
    exam: "说明三种加工对 mRNA 稳定性、输出与翻译的意义，并解释可变剪接如何扩展蛋白质多样性。",
  },
  {
    ...shared, id: "translation", label: "翻译", short: "TL", x: 71, y: 60, size: 72, subject: "cross", priority: 3, mode: "information", source: "河南农既有大纲",
    summary: "核糖体按 mRNA 密码子顺序读取氨酰-tRNA，经历起始、延伸、终止合成多肽。",
    location: "胞质游离核糖体或粗面 ER 结合核糖体",
    equation: "氨基酸活化消耗 ATP→AMP；每延伸 1 个残基另消耗 2 GTP",
    enzymes: [{ name: "氨酰-tRNA合成酶", note: "识别氨基酸与对应 tRNA，并具有编辑功能", type: "遗传密码准确性" }, { name: "肽基转移酶中心", note: "由大亚基 rRNA 催化，是核酶", type: "肽键形成" }],
    flags: ["密码子", "摆动配对", "核酶", "能量消耗"],
    exam: "按 A/P/E 位点解释延伸循环，并计算合成 n 肽所需高能磷酸键数。",
  },
  {
    ...shared, id: "ribosome", label: "核糖体", short: "RIBO", x: 88, y: 75, size: 68, subject: "cross", priority: 3, mode: "information", source: "河南农既有大纲",
    summary: "rRNA 与蛋白质组成的核糖核蛋白机器；小亚基解码，大亚基催化肽键。",
    location: "游离于胞质或附着粗面 ER；线粒体/叶绿体有自身核糖体",
    equation: "原核 70S = 30S + 50S；真核胞质 80S = 40S + 60S",
    enzymes: [{ name: "23S/28S rRNA", note: "构成肽基转移酶中心", type: "核酶" }],
    flags: ["A/P/E位点", "多核糖体", "核酶", "抗生素靶点"],
    exam: "比较原核与真核核糖体及起始机制，说明抗生素选择性作用的基础。",
  },
  {
    ...shared, id: "nucleus", label: "细胞核", short: "NUC", x: 71, y: 19, size: 72, subject: "cell", priority: 3, mode: "information", source: "同类农校预测",
    summary: "双层核膜包围染色质；核孔复合体执行选择性核质运输，核仁负责核糖体亚基发生。",
    location: "真核细胞遗传与转录控制中心",
    equation: "NLS货物 + importin → 核孔运输；Ran-GTP 梯度赋予方向性",
    enzymes: [{ name: "Ran GTPase", note: "核内 Ran-GTP 高、胞质 Ran-GDP 高，决定运输方向", type: "分子开关" }],
    flags: ["核膜", "核孔", "核纤层", "核仁"],
    exam: "解释 Ran 梯度如何分别驱动核输入和核输出，并比较小分子被动扩散。",
  },
  {
    ...shared, id: "nuclear-pore", label: "核孔复合体", short: "NPC", x: 91, y: 23, subject: "cell", priority: 3, mode: "information", source: "同类农校预测",
    summary: "贯穿双层核膜的选择性运输机器，小分子可扩散，大分子货物依赖核转运受体。",
    location: "内外核膜融合处",
    equation: "FG-核孔蛋白形成选择性屏障",
    enzymes: [{ name: "Importin / Exportin", note: "识别 NLS/NES，并由 Ran 调控货物结合", type: "核转运受体" }],
    flags: ["NLS", "NES", "Ran梯度", "选择性运输"],
    exam: "给定 NLS 突变或 Ran 调控异常，预测蛋白亚细胞定位。",
  },
  {
    ...shared, id: "operon", label: "乳糖操纵子", short: "lac", x: 42, y: 16, size: 68, subject: "biochem", priority: 3, mode: "information", source: "河南农既有大纲",
    summary: "负调控与正调控叠加的原核诱导型操纵子：无乳糖时阻遏，有乳糖且低葡萄糖时高表达。",
    location: "原核生物基因组与胞质转录系统",
    equation: "乳糖→异乳糖解除阻遏；低葡萄糖→cAMP-CAP促进转录",
    enzymes: [{ name: "β-半乳糖苷酶", note: "lacZ产物，水解乳糖并生成诱导物异乳糖", type: "结构基因产物" }],
    flags: ["负诱导", "分解代谢物阻遏", "CAP-cAMP", "多顺反子"],
    exam: "用四种‘葡萄糖±/乳糖±’组合判断 lac 操纵子表达水平并说明原因。",
  },
  {
    ...shared, id: "gpcr", label: "GPCR", short: "GPCR", x: 85, y: 45, size: 66, subject: "cross", priority: 3, mode: "information", source: "同类农校预测",
    summary: "七次跨膜受体激活异三聚体 G 蛋白，把胞外配体信号转成第二信使变化。",
    location: "质膜",
    equation: "配体→GPCR→Gα GDP换GTP→腺苷酸环化酶→cAMP→PKA",
    enzymes: [{ name: "Gαs", note: "激活腺苷酸环化酶；自身 GTPase 活性关停信号", type: "分子开关" }],
    flags: ["7TM", "GTP开关", "信号放大", "脱敏"],
    exam: "画出 GPCR-cAMP 通路，并写出至少三处关停/脱敏机制。",
  },
  {
    ...shared, id: "camp", label: "cAMP", short: "cAMP", x: 93, y: 52, size: 54, subject: "cross", priority: 3, mode: "information", source: "同类农校预测",
    summary: "由 ATP 生成的第二信使，激活 PKA 并快速放大激素信号。",
    location: "胞质局部微区",
    equation: "ATP → cAMP + PPi；cAMP → 5′-AMP",
    enzymes: [{ name: "腺苷酸环化酶", note: "合成 cAMP", type: "第二信使生成" }, { name: "磷酸二酯酶", note: "降解 cAMP 并终止信号", type: "关停" }],
    flags: ["第二信使", "PKA", "快速放大", "PDE降解"],
    exam: "预测霍乱毒素或磷酸二酯酶抑制剂对 cAMP 与下游反应的影响。",
  },
  {
    ...shared, id: "ubiquitin", label: "泛素", short: "Ub", x: 58, y: 86, subject: "cross", priority: 3, mode: "information", source: "同类农校预测",
    summary: "76 aa 小蛋白，通过 E1-E2-E3 级联共价连接到底物；不同链型决定降解或信号命运。",
    location: "胞质与细胞核",
    equation: "E1活化（ATP）→E2转运→E3识别底物并连接 Ub",
    enzymes: [{ name: "E3泛素连接酶", note: "决定底物特异性，是调控的关键层", type: "蛋白质降解标记" }],
    flags: ["E1/E2/E3", "ATP依赖", "K48链", "可逆修饰"],
    exam: "说明泛素化为何既能标记降解又能参与信号，并联系细胞周期调控。",
  },
  {
    ...shared, id: "proteasome", label: "蛋白酶体", short: "26S", x: 32, y: 87, size: 66, subject: "cross", priority: 3, mode: "information", source: "同类农校预测",
    summary: "26S 蛋白酶体识别多聚泛素化底物，去泛素、展开并将蛋白送入 20S 核心降解。",
    location: "胞质与细胞核；非膜性复合体",
    equation: "泛素化蛋白 + ATP → 小肽 + 回收泛素",
    enzymes: [{ name: "19S调节颗粒", note: "识别、去泛素并以 ATPase 展开底物", type: "底物处理" }],
    flags: ["ATP依赖", "非溶酶体", "短寿命蛋白", "质量控制"],
    exam: "比较泛素-蛋白酶体与溶酶体/自噬的底物、选择性、能量和区室。",
  },
  {
    ...shared, id: "rer", label: "粗面内质网", short: "RER", x: 88, y: 85, size: 62, subject: "cell", priority: 3, mode: "information", source: "同类农校预测",
    summary: "分泌蛋白和膜蛋白通过 SRP 介导的共翻译转位进入 ER 腔或插入膜。",
    location: "核外膜连续区域，胞质侧附着核糖体",
    equation: "信号肽→SRP暂停→对接SRP受体→Sec61转位→翻译恢复",
    enzymes: [{ name: "SRP GTPase", note: "SRP 与受体对接、交接核糖体后水解 GTP", type: "靶向" }],
    flags: ["信号肽", "SRP", "共翻译转位", "Sec61"],
    exam: "追踪一个含 N 端信号肽的分泌蛋白从翻译起始到进入 ER 腔。",
  },
  {
    ...shared, id: "dna-repair", label: "DNA损伤修复", short: "REPAIR", x: 19, y: 29, size: 64, subject: "biochem", priority: 3, mode: "information", source: "河南农资料高频",
    summary: "复制保真度由碱基选择、3′→5′校对和复制后修复层层保障；不同损伤由直接修复、切除修复、错配修复或双链断裂修复处理。",
    location: "细胞核/拟核；常与复制叉和细胞周期检查点协同",
    equation: "识别损伤 → 切除/逆转 → DNA聚合酶补缺 → DNA连接酶封口",
    enzymes: [{ name: "碱基切除修复", note: "DNA糖基化酶先移除异常碱基，再经 AP 位点修补", type: "BER" }, { name: "核苷酸切除修复", note: "切除含损伤的一段寡核苷酸，适合体积较大损伤", type: "NER" }],
    flags: ["校对≠修复", "BER/NER", "错配修复", "双链断裂"],
    exam: "比较 DNA Pol I 的修补作用与 Pol III 的主要复制作用，或按损伤类型匹配修复机制。",
  },
  {
    ...shared, id: "reverse-transcription", label: "逆转录", short: "RT", x: 48, y: 50, size: 61, subject: "biochem", priority: 2, mode: "information", source: "河南农课件",
    summary: "以 RNA 为模板合成 DNA，说明遗传信息流存在 RNA→DNA 的补充方向；逆转录酶还具有 RNase H 活性。",
    location: "逆转录病毒复制与实验室 cDNA 合成",
    equation: "RNA → RNA/DNA杂交体 → 双链DNA",
    enzymes: [{ name: "逆转录酶", note: "RNA依赖的DNA聚合酶，保真度通常低于细胞DNA聚合酶", type: "模板转换" }],
    flags: ["RNA→DNA", "cDNA", "RNase H", "端粒酶相关"],
    exam: "说明逆转录不是否定中心法则，而是信息传递的特殊补充方向。",
  },
  {
    ...shared, id: "trp-operon", label: "色氨酸操纵子", short: "trp", x: 63, y: 9, size: 61, subject: "biochem", priority: 3, mode: "information", source: "河南农资料高频",
    summary: "合成型可阻遏操纵子：色氨酸充足时作为辅阻遏物抑制转录，并通过衰减机制根据带电 tRNAᵀʳᵖ 水平精细调节。",
    location: "原核生物转录-翻译偶联环境",
    equation: "Trp高：阻遏 + 3-4终止发卡；Trp低：核糖体停顿 + 2-3反终止发卡",
    enzymes: [{ name: "前导肽 / 衰减子", note: "把翻译速度转化为转录是否提前终止", type: "衰减调控" }],
    flags: ["合成型", "可阻遏", "衰减", "转录翻译偶联"],
    exam: "与 lac 操纵子对比诱导/阻遏、正负调控和营养物高低时的表达逻辑。",
    crossLinks: [{ id: "operon", question: "用表格比较 lac 与 trp 操纵子的代谢类型、效应物、阻遏蛋白状态与表达场景。" }],
  },
];

export const edges: Record<Mode, [string, string][]> = {
  foundation: [
    ["amino-acid", "isoelectric-point"], ["amino-acid", "peptide-bond"], ["peptide-bond", "protein-structure"],
    ["protein-structure", "alpha-helix"], ["protein-structure", "denaturation"], ["protein-structure", "hemoglobin"],
    ["protein-structure", "protein-purification"], ["isoelectric-point", "protein-purification"],
    ["nucleic-acid", "dna-denaturation"], ["nucleic-acid", "protein-structure"], ["nucleic-acid", "enzyme"],
    ["enzyme", "michaelis"], ["michaelis", "enzyme-inhibition"], ["enzyme", "coenzyme"],
    ["coenzyme", "enzyme-inhibition"], ["enzyme", "protein-structure"],
  ],
  metabolism: [
    ["g6p", "glycolysis"], ["g6p", "ppp"], ["ppp", "g6pd"], ["ppp", "nadph"], ["ppp", "glycolysis"],
    ["g6p", "glycogen-starch"], ["glycolysis", "gluconeogenesis"], ["gluconeogenesis", "oaa"],
    ["glycolysis", "substrate-phosphorylation"], ["tca", "substrate-phosphorylation"],
    ["glycolysis", "pep"], ["glycolysis", "pyruvate"], ["pep", "pyruvate"], ["pyruvate", "acetyl"], ["acetyl", "tca"],
    ["tca", "oaa"], ["tca", "nadh"], ["tca", "etc"], ["oaa", "glyoxylate"], ["glyoxylate", "tca"],
    ["beta-oxidation", "acetyl"], ["beta-oxidation", "tca"], ["nadph", "fatty-acid-synthesis"], ["fatty-acid-synthesis", "acetyl"],
    ["nadh", "etc"], ["etc", "atp-synthase"], ["nadh", "malate-shuttle"], ["etc", "uncoupling"],
    ["beta-oxidation", "ketone-body"], ["acetyl", "ketone-body"], ["acetyl", "cholesterol"],
  ],
  nitrogen: [
    ["aa-pool", "transamination"], ["transamination", "plp"], ["transamination", "glutamate"],
    ["glutamate", "oxidative-deamination"], ["oxidative-deamination", "urea-cycle"], ["urea-cycle", "cps1"],
    ["aa-pool", "one-carbon"], ["glutamate", "gs-gogat"], ["one-carbon", "purine"], ["one-carbon", "pyrimidine"],
    ["prpp", "purine"], ["prpp", "pyrimidine"], ["purine", "rnr"], ["pyrimidine", "rnr"],
    ["cps1", "pyrimidine"], ["prpp", "gs-gogat"],
  ],
  cell: [
    ["membrane", "phospholipid"], ["membrane", "transport"], ["membrane", "signaling"], ["membrane", "cytoskeleton"],
    ["membrane", "mitochondria"], ["mitochondria", "apoptosis"], ["mitochondria", "peroxisome"], ["chloroplast", "peroxisome"],
    ["chloroplast", "vacuole"], ["er", "golgi"], ["golgi", "lysosome"], ["er", "membrane"], ["golgi", "membrane"],
    ["cytoskeleton", "microtubule"], ["cytoskeleton", "actin"], ["cytoskeleton", "cell-cycle"], ["microtubule", "cell-cycle"],
    ["cell-cycle", "apoptosis"], ["cell-wall", "cytoskeleton"], ["vacuole", "cell-wall"], ["signaling", "cell-cycle"],
  ],
  information: [
    ["dna", "replication"], ["replication", "dna-pol"], ["dna-pol", "dna-repair"], ["dna", "dna-repair"],
    ["dna", "transcription"], ["transcription", "rna-pol"], ["dna", "reverse-transcription"],
    ["transcription", "mrna"], ["mrna", "translation"], ["translation", "ribosome"], ["translation", "rer"],
    ["dna", "nucleus"], ["nucleus", "nuclear-pore"], ["mrna", "nuclear-pore"], ["dna", "operon"], ["operon", "trp-operon"],
    ["gpcr", "camp"], ["camp", "transcription"], ["ubiquitin", "proteasome"], ["translation", "ubiquitin"],
    ["ubiquitin", "dna"], ["rer", "ribosome"],
  ],
};

export const chapters = [
  { title: "01 绪论与代谢总论", subject: "生物化学", count: 18, priority: "基础", note: "研究对象、代谢共同规律、自由能与高能化合物" },
  { title: "02 蛋白质", subject: "生物化学", count: 45, priority: "必攻", note: "氨基酸、等电点、结构层次、变性复性、分离纯化" },
  { title: "03 核酸", subject: "生物化学", count: 28, priority: "必攻", note: "核苷酸、DNA/RNA结构、Tm、增色效应与核酸杂交" },
  { title: "06 酶", subject: "生物化学", count: 34, priority: "必攻", note: "全酶、活性中心、米氏动力学、抑制与调节" },
  { title: "07 维生素", subject: "生物化学", count: 17, priority: "高", note: "维生素—辅酶形式—转移基团—代表反应四联表" },
  { title: "08 生物氧化", subject: "生物化学", count: 33, priority: "必攻", note: "呼吸链、氧化磷酸化、穿梭、抑制剂、P/O与能量" },
  { title: "09 糖及糖代谢", subject: "生物化学", count: 48, priority: "必攻", note: "EMP、TCA、PPP、糖异生、糖原/淀粉与乙醛酸循环" },
  { title: "10 脂及脂代谢", subject: "生物化学", count: 36, priority: "必攻", note: "脂肪动员、β氧化、脂肪酸合成、酮体与胆固醇" },
  { title: "11 氨基酸代谢", subject: "生物化学", count: 38, priority: "必攻", note: "转氨、联合脱氨、尿素循环、一碳单位与氨同化" },
  { title: "12 核苷酸代谢", subject: "生物化学", count: 24, priority: "高", note: "PRPP、嘌呤/嘧啶从头与补救合成、dNTP生成" },
  { title: "13 DNA的生物合成", subject: "生物化学", count: 30, priority: "必攻", note: "半保留与半不连续复制、复制酶、拓扑与损伤修复" },
  { title: "14 RNA生物合成", subject: "生物化学", count: 28, priority: "高", note: "转录、RNA聚合酶、加工、操纵子与表达调控" },
  { title: "15 蛋白质生物合成", subject: "生物化学", count: 32, priority: "必攻", note: "遗传密码、tRNA、核糖体、翻译步骤、能量与抑制剂" },
];

export const findNode = (id: string) => nodes.find((node) => node.id === id);
